# DP Hyperparameters

dp:
  method: "dp_sgd" # one of -> ["dp_sgd", "pate", "naive_noise"]

  target_epsilon: 8.0
  target_delta: 1e-5
  max_grad_norm: 1.0

dp_sgd:
  noise_multiplier: 1.2
  microbatch_size: 64
  # Example: for Opacus-based training
  # More hyperparameters -> https://opacus.ai/api/compute_dp_sgd_privacy.html

pate:
  # Example PATE config
  teachers_count: 10
  laplace_scale: 0.2


naive_noise:
  sigma: 0.01

training:
  epochs: 10
  lr: 0.001
  weight_decay: 0.0001

paths:
  model_save_dir: "./models"
  