# Optimized Model configuration
model:
  architecture: "resnet18_dp"  # DP-compatible ResNet18-like architecture
  num_classes: 10
  pretrained: false  # DP-compatible model doesn't use pretrained weights
  dropout_rate: 0.2

# Dataset configuration
data:
  dataset: "cifar10"  # Options: cifar10, cifar100, mnist
  train_batch_size: 512     # Larger batch size for better privacy-utility tradeoff
  eval_batch_size: 512
  num_workers: 4

# Attack configuration - optimized for reasonable runtime
attack:
  attack_type: "all"  # Will run all attacks
  features:
    - "max_prob"
    - "true_class_prob"
    - "entropy"
    - "loss"
    - "margin"
  
  # Shadow attack specific - reduced for faster execution
  shadow:
    num_shadows: 8       # Reduced from 32 - still good attack quality
    epochs: 10           # Reduced from 20 - sufficient for good models
    batch_size: 128
    learning_rate: 0.001
    shadow_train_size: 5000   # Reduced from 10000 - faster training
    shadow_eval_size: 2500    # Reduced from 5000 - faster evaluation
  
  # Loss attack specific
  loss:
    threshold: 0.5
  
  # Population attack specific - optimized
  population:
    num_reference: 5
    reference_size: 5000      # Reduced from 10000 - faster baseline computation

# Defense configuration - for each method we'll test
defense:
  # Will be overridden by command line args
  method: "opacus_dp_sgd"  # Updated to use Opacus implementation
  epsilon: 1.0  # We'll test 0.1, 1.0, 3.0, 10.0, inf
  delta: 1e-5
  max_grad_norm: 1.0
  noise_multiplier: 1.0
  max_physical_batch_size: 128  # New parameter for Opacus memory management

# Training configuration - optimized for DP training
training:
  epochs: 20               # Increased for better accuracy - DP models need more training
  learning_rate: 0.01      # Higher LR for DP training (noise requires stronger signal)
  optimizer: "sgd"         # SGD works better with DP than Adam
  weight_decay: 0.0001

# Output configuration
output:
  save_dir: "./results/full"
  visualizations: true

# General
seed: 42